# Configuration for v0.2.0 and later

tm_jsonrpc="http://devnet-verifiers.axelar.dev:26657"
tm_grpc="tcp://devnet-verifiers.axelar.dev:9090"
event_buffer_cap=1000

[service_registry]
cosmwasm_contract="axelar1qk00h5atutpsv900x202pxx42npjr9thg58dnqpa72f2p7m2luas9x8txw"

[broadcast]
batch_gas_limit="1000000"
broadcast_interval="1s"
chain_id="devnet-verifiers"
gas_adjustment="2"
gas_price="0.00005uverifiers"
queue_cap="1000"
tx_fetch_interval="600ms"
tx_fetch_max_retries="10"

[tofnd_config]
batch_gas_limit="10000000"
key_uid="axelar"
party_uid="ampd"
url="http://127.0.0.1:50051"

[[handlers]]
cosmwasm_contract="axelar15nczwuqh0zcu6syeqsc4td6dphql7n2p7cgkl9raz97z5s3zdjrsc8we9y"
type="MultisigSigner"

[[handlers]]
chain_name="avalanche"
chain_rpc_url="https://avalanche-fuji-c-chain-rpc.publicnode.com"
cosmwasm_contract="axelar1elaymnd2epmfr498h2x9p2nezc4eklv95uv92u9csfs8wl75w7yqdc0h67"
type="EvmMsgVerifier"

[[handlers]]
chain_name="fantom"
chain_rpc_url="https://rpc.ankr.com/fantom_testnet/"
cosmwasm_contract="axelar17fa8wruwmk2y0h32wrg5rxwespvcvz5zc2hjnczz58tnmg8enh0sunsshp"
type="EvmMsgVerifier"
